# Generated by Django 3.2.25 on 2024-09-17 05:50

from django.db import migrations

def transfer_receiver_foreignkeys(apps, schema_editor):
    Notification = apps.get_model('notifications', 'Notification')

    for notif in Notification.objects.all():
        if notif.receiver:
            notif.receivers.add(notif.receiver)


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_receivers'),
    ]

    operations = [
        migrations.RunPython(transfer_receiver_foreignkeys)
    ]
