# Generated by Django 3.2.25 on 2024-09-18 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0005_remove_notification_receiver'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_list', models.JSONField(default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='channels_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
