# Generated by Django 3.2.25 on 2024-09-18 13:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0006_channellist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChannelList',
            new_name='ChannelGroupList',
        ),
    ]
