# Generated by Django 3.2.25 on 2024-09-18 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_rename_channellist_channelgrouplist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channelgrouplist',
            old_name='channel_list',
            new_name='group_list',
        ),
    ]
