# Generated by Django 3.2.25 on 2024-09-24 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0008_rename_channel_list_channelgrouplist_group_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelgrouplist',
            name='group_list',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='channelgrouplist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='channel_groups_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
