# Generated by Django 3.2.25 on 2024-09-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_question_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='subscribers',
            field=models.JSONField(default=list),
        ),
    ]
