# Generated by Django 3.2.25 on 2025-02-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20250207_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='upvotes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='answer',
            name='downvoted_by',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='answer',
            name='upvoted_by',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='question',
            name='downvoted_by',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='question',
            name='upvoted_by',
            field=models.JSONField(default=list),
        ),
    ]
