version: '3'

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j-questify
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASS}
      # - NEO4JLABS_PLUGINS=["apoc"]
      # - NEO4J_apoc_export_file_enabled=true
      # - NEO4J_apoc_import_file_enabled=true
      # - NEO4J_apoc_import_file_use__neo4j__config=true
    ports:
      - '7474:7474'
      - '7687:7687'
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_plugins:/plugins
      - neo4j_import:/import

volumes:
  neo4j_data:
  neo4j_plugins:
  neo4j_logs:
  neo4j_import:
